### PR TITLE
Small fix and a few tweaks

### PR DESCRIPTION
**Pull request by krishna-v**
Hi Tim, Thanks for creating hue-bridge-emulator. I've done a few small tweaks, namely:
- Added the ability to set port and toggle debug at instantiation.
- Fixed deep copy of the template json (hueColorLamp) to make multiple bulbs work correctly.

Cheers!
Krishna

### CODE REVIEW

**Comment by tim-hellhake** [comment]
Hi @krishna-v, thanks for the contribution!

> Added the ability to set port

Did you check if this works with a port other than 80?
I'm asking because when I developed the emulator, my Echo ignored the advertised port completely.
All requests came in on port 80.

**Comment by krishna-v** [comment]
I ran the emulator on port 8080 and could successfully execute curl
commands against it. The actual Echo device (with recent firmware at least)
only connects on port 80. Earlier firmwares used to allow different ports.

Cheers!

**Comment by tim-hellhake** [comment]
> The actual Echo device (with recent firmware at least)
only connects on port 80

Do you have a use case for the emulator besides the echo?

**Comment by krishna-v** [comment]
No am looking to pair it with my echo, but I want to run my app as
non-root, so I'll be running the actual app on port 8080, and using an
iptables rule to redirect traffic from port 80 to 8080. This is safer, IMHO.

**Comment by krishna-v** [comment]
Hi Tim,
am looking at making some changes to callback handling which will break current behaviour. Instead of passing individual key value pairs to the callback one at a time, am looking at implementing a single callback that will pass the payload, so that more intelligent processing can be done by e.g. looking at HSB values together. Is this a major problem for you?
Also looking at enhancing addLight so that one can set different types of lights, e.g. simple dimming, color temperature, etc.
Let me know if you need to preserve current callback behaviour. This should be possible if necessary, but will introduce some code complexity.

Thanks.

**Pull request closed without merging**
